# Generated by Django 4.2.4 on 2023-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
